image: rust:1.34

pipelines:
  custom:
    default:
      - step:
          script:
            - apt-get update
            - apt-get install -y libasound2-dev
            - cargo build -v --release
            - cargo test -v
